apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "my-gitlab-group-creds-template"
  namespace: "argocd"
spec:
  refreshInterval: "15m"
  secretStoreRef:
    kind: ClusterSecretStore
    name: "your-cluster-secret-store" # e.g., vault-backend

  # This is where the magic happens: define the K8s secret
  target:
    name: "my-gitlab-group-creds-template"
    template:
      type: Opaque
      metadata:
        labels:
          # This label tells ArgoCD to treat this as repo credentials
          "argocd.argoproj.io/secret-type": "repo-creds"
      data:
        # ArgoCD will use these creds for any repo matching this URL prefix
        "url": "https://gitlab.com/yourcompany/teamone"
        "username": "argocd"
        # The password/token is templated from the data fetched below
        "password": "{{ .token | toString }}"

  # This section defines what to fetch from your external secret store
  data:
  - secretKey: "token"
    remoteRef:
      # Path to the secret in your external provider
      key: "gitlab/my-gitlab-group/group-access-token"
      property: "token"
