apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: testteam-argo-access-token-credentials
  namespace: crossplane-system
spec:
  data:
  - conversionStrategy: None
    match:
      remoteRef:
        remoteKey: gitlab/testteam/argo-access-token # Path in Vault where the secret will be stored
    metadata:
      managed-by: external-secrets
  deletionPolicy: None # Don't delete the secret in Vault if this PushSecret is deleted
  refreshInterval: '5m'
  secretStoreRefs:
  - kind: ClusterSecretStore # Reference to the Secret Store (Vault)
    name: platform
  selector:
    secret:
      name: testteam-argo-access-token-credentials # Name of the Kubernetes Secret that should be pushed to Vault
  updatePolicy: Replace


